---
mqtt_settings:
  host: mosquitto
  port: 1883
  command_topic: commands/#  # We subscribe to this MQTT topic to receive commands
  error_topic: error  # If this has a value, we publish error messages under this MQTT topic
modbus_settings:
  host: pymodbus
  port: 5020
modbus_mapping:
  ## name        - the variable name
  ## byte_order  - the ordering of bytes
  ##  |---AB, ABCD   - Big Endian
  ##  |---BA, DCBA   - Little Endian
  ##  |---BADC       - Mid-Big Endian
  ##  |---CDAB       - Mid-Little Endian
  ## data_type   - INT8L, INT8H, UINT8L, UINT8H (low and high byte variants)
  ##               INT16, UINT16, INT32, UINT32, INT64, UINT64,
  ##               FLOAT16-IEEE, FLOAT32-IEEE, FLOAT64-IEEE (IEEE 754 binary representation)
  ##               FLOAT32, FIXED, UFIXED (fixed-point representation on input)
  ## scale       - the final numeric variable representation
  ## address     - variable address
  holding_registers:
    - name: evgBatteryMode
      byte_order: AB  # Fill this in
      data_type: INT16  # Fill this in
      scale: 1.0  # Fill this in
      address: [0]  # Fill this in with actual Modbus register address for evgBatteryMode
    - name: evgBatteryTargetPowerWatts
      byte_order: AB  # Fill this in`
      data_type: INT16  # Fill this in
      scale: 1.0  # Fill this in
      address: [1]  # Fill this in with actual Modbus register address for evgBatteryTargetPowerWatts
    - name: evgBatteryTargetSOCPercent
      byte_order: AB  # Fill this in
      data_type: INT16  # Fill this in
      scale: 1.0  # Fill this in
      address: [2]  # Fill this in with actual Modbus register address for evgBatteryTargetSOCPercent
    - name: testRegister
      byte_order: AB  # Fill this in
      data_type: INT16  # Fill this in
      scale: 1.0  # Fill this in
      address: [1]  # Fill this in with actual Modbus register address for evgBatteryTargetPowerWatts
    - name: testFloatRegister
      byte_order: AB  # Fill this in
      data_type: FLOAT32-IEEE  # Fill this in
      scale: 1.0  # Fill this in
      address: [2]  # Fill this in with actual Modbus register address for evgBatteryTargetPowerWatts
    - name: testFloat64Register
      byte_order: AB  # Fill this in
      data_type: FLOAT64-IEEE  # Fill this in
      scale: 1.0  # Fill this in
      address: [3]  # Fill this in with actual Modbus register address for evgBatteryTargetPowerWatts
    - name: testInt64Register
      byte_order: AB  # Fill this in
      data_type: INT64  # Fill this in
      scale: 1.0  # Fill this in
      address: [20]  # Fill this in with actual Modbus register address for evgBatteryTargetPowerWatts
    - name: testUInt64Register
      byte_order: AB  # Fill this in
      data_type: UINT64  # Fill this in
      scale: 1.0  # Fill this in
      address: [30]  # Fill this in with actual Modbus register address for evgBatteryTargetPowerWatts
  coils:
    - name: evgBatteryModeCoil  # Assuming 'evgBatteryMode' is also represented as a coil
      address: [501]  # Fill this in with actual Modbus register address for the coil
    - name: evgBatteryTargetPowerWattsCoil  # Assuming 'evgBatteryTargetPowerWatts' is also represented as a coil
      address: [502]  # Fill this in with actual Modbus register address for the coil
    - name: evgBatteryTargetSOCPercentCoil  # Assuming 'evgBatteryTargetSOCPercent' is also represented as a coil
      address: [503]  # Fill this in with actual Modbus register address for the coil
