---
name: end-to-end
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install -v
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Run containers
        run: |
          docker-compose up -d
      - name: Run end to end tests
        run: |
          poetry run coverage run -m pytest -m end_to_end
      - name: Stop containers
        run: |
          docker-compose down
