---
name: Test & Linting
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install -v
      - name: Lint with pylint
        run: |
          poetry run pylint -E --rcfile=./.pylintrc app/ main.py
      - name: Check code formatting with Black
        run: |
          poetry run black --check .
      - name: Test with pytest
        run: |
          poetry run  coverage run --source=main.py --source=app -m pytest -m "not end_to_end"
      - name: Report coverage with Coveralls
        run: |
          poetry run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
